# Generated by Django 4.0.6 on 2022-07-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_cep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultarcep',
            name='complemento',
        ),
    ]
