# Generated by Django 4.0.5 on 2022-07-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador_cep', '0002_remove_consultarcep_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, unique=True)),
                ('logradouro', models.CharField(blank=True, max_length=256, null=True)),
                ('complemento', models.CharField(blank=True, max_length=256, null=True)),
                ('bairro', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
                ('sigla', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsultarCep',
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buscador_cep.estado'),
        ),
        migrations.AddField(
            model_name='cep',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buscador_cep.cidade'),
        ),
    ]
