version: '2.4'

services:

    postgres_local:
      container_name: "postgres"
      image: "postgres:13.3-alpine"
      ports:
        - "8080:5432"
      env_file:
        - .env
      volumes:
        - ./.postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: